/*
 * LispScript.idl ---
 *
 *    This IDL file isn't used for anything right now. I just use it to track
 *    the classes and interfaces implemented so far. This allows me to more
 *    easily track the current degree of CORBA-compatibility of the
 *    implementation. Once the design of interpreter has reached some level
 *    of stability it will be completely based on CORBA, hopefully removing
 *    design flaws. Basing the implementation of CORBA will, for example,
 *    allow dynamic loading of class implementation at run-time or 
 *    dynamically constructing method calls.
 *
 * (c) 1999 by Michael Saure
 * RCSID: $Id: lispel.idl,v 1.1.1.1 2001/10/31 15:44:42 michael Exp $
 */

module lscript {

  enum InterpreterMode { imSAFE, imLIMITEDREAD, imFULL };

  interface Interpreter {
     string evalExpression( in string expr);
  }; /*interface SystemFactory*/

  interface Factory {
     Interpreter makeInterpreter( in InterpreterMode im);
  }; /*interface Factory*/


}; /*module lscript*/

