.TH KDOC 1 "$Version" "29 March 1998"
.SH NAME
.B KDOC 
\- C\+\+ Class Documentation Extraction and Generation Tool
.SH SYNOPSIS
.B kdoc
[\-H][\-M][\-T] [\-d <output dir>][\-u <url>] [\-a][\-p] [\-e][\-i] [\-q]
[\-L <libpath>] <libname> <header>... [-l<crossref lib>]...
.SH DESCRIPTION
.B KDOC
uses specially\-formatted documentation embedded in C++ class declarations
to generate documentation for the classes.
.PP
.B KDOC 
can generate cross\-referenced HTML pages, LaTeX documents and man
pages documenting your classes (see
.B "CROSS-REFERENCING LIBRARIES"
for cross-referencing information).

.PP
.B KDOC
can also correctly handle the
.I signals
and
.I slots
specifiers that used by the
.I "Qt GUI Toolkit."

.SH OPTIONS
.TP
.B \-H
Generate HTML pages (default).

.TP
.B \-T
Generate LaTeX output.

.TP
.B \-M
Generate man pages.

.TP
.B "\-d <output dir>"
Specify directory for output files.

.TP
.B "\-u <url>"
Specify the base URL by which the generated documentation can
be accessed. This will be saved in the cross-referencing information
for this library and will be used by libraries wishing to link their
documentation to this library.

.TP
.B "\-a"
Include members and classes in documentation even if they don't have
an explicit documentation tag.

.TP
.B "\-p"
Include private members in documentation. These are skipped by default.

.TP
.B "\-e"
Do not include deprecated (
.B "\@deprecated"
tag) members and classes in the documentation.

.TP
.B "\-i"
Do not include internal (
.B "\@internal"
tag) members and classes in the documentation.

.TP
.B "\-q"
Proceed quietly (suppress all but error messages).

.TP
.B "\-L <dir>"
Specify the path to read and write
.B ".kdoc"
cross-reference libraries. This overrides the 
.B $KDOCLIBS 
environment variable.

.SH "CROSS-REFERENCING LIBRARIES"
.B KDOC
allows documentation from one class to refer to classes and
members in other classes. It also allows documentation from
one set of classes (a "library") to refer to documentation
generated for another library. 

As an example, the
.I "KDE Project"
uses
.B KDOC
to link the HTML documentation for it's libraries with
the documentation of the 
.I "Qt Toolkit."
Wherever the KDE documentation refers to the
.I QObject
class, the HTML output contains hyperlinks to the
.I QObject
documentation, even though it is not part of the KDE library.

To do this,
.B KDOC
generates a cross-reference file with a
.I ".kdoc"
extension whenever you process a set of header files. Then, when
you wish to cross-reference documentation from another library
to this one, you can simply use the 
.B "-l<libname>"
option, assuming the
.I .kdoc
file is named 
.I "<libname>.kdoc"
and you have specified the path to the 
.I ".kdoc"
files with the 
.B "-L<path>"
option.
.SH FILES
.TP
.B "<library>.kdoc"
These files are used by
.B KDOC
to allow other libraries to cross-reference with this one.
.TP
.B "index.html"
Class Index, generated by the
.I HTML 
output option.

.TP
.B "hier.html"
Class Heirarchy chart, generated by the
.I HTML
output otion.

.TP
.B "<classname>.html"
Documentation for a single class and its members, generated by
the
.I HTML
output option.

.TP
.B "*-h.html"
HTML version of library headers, generated by the 
.I HTML
output option.

.TP
.B "<library>.tex"
LaTeX documentation for the library, generated by the
.I LaTeX
output option.

.TP
.B "<library>.1"
Index man page for the library, generated by the
.I "man page"
output option.

.TP
.B "<classname>.3"
Man page documenting the class and its members, generated by
the
.I "man page"
output option.

.SH ENVIRONMENT
.TP
.B "KDOCLIBS"	
If the search path for the cross\-reference files is not specified
using the 
.B "-L"
option,
.B KDOC
looks for and uses the path specified by the
.B "KDOCLIBS"
environment variable.

.SH "SEE ALSO"
qt2kdoc(1), latex(1)

.SH BUGS
Incorrect handling of inner classes.

.SH AUTHOR
.B KDOC 
and this man page were written by Sirtaj Singh Kang <taj@kde.org>
and Torben Weis <weis@kde.org>.
