# Generated automatically from Makefile.in by configure.
CC		= gcc
CXX		= c++
CFLAGS		= -g -O2
CXXFLAGS	= -g -O2

RM		= rm -f

EXEEXT		= 

testprogs	= chartypes$(EXEEXT)

all:		$(testprogs)

.cc.o:
	$(CXX) $(CXXFLAGS) -c $<


chartypes$(EXEEXT):	chartypes.o
	$(CXX) -o chartypes$(EXEEXT) chartypes.o

